ft/login-page
atlp-rwanda/cabal-bn-fe pull request #10
Opened 2022-05-05 22:28 UTC by Gabin-ishimwe

2022-05-07 20:05 UTC, ncutixavier commented
Your test coverage is good for now. Just work on Axios interceptor, you may refer to this link https://axios-http.com/docs/interceptors

2022-05-08 11:19 UTC, Code-250 reviewed
do not mix async await with .then and .catch promises since both do the same thing consider using one of them.

2022-05-08 11:19 UTC, Code-250 commented on src/redux/actions/auth.js
> +  return async (dispatch) => {
if you are going to use async consider await using await not .then with async

2022-05-09 09:58 UTC, Eli250 approved these changes

2022-05-09 11:26 UTC, Code-250 approved these changes

2022-05-10 08:02 UTC, ncutixavier requested changes

2022-05-10 08:08 UTC, ncutixavier commented
![image](https://user-images.githubusercontent.com/51375428/167580331-bb8126ff-a8c3-4238-b7a1-4782efd28a89.png)
Show sign-out only when user logged in

2022-05-10 08:08 UTC, ncutixavier commented
Also work on your footer

2022-05-10 09:08 UTC, ncutixavier commented
Have you forgotten the naming convention? because It seems like your PR title does not format well and your PR description doesn't look well

2022-05-10 09:18 UTC, Gabin-ishimwe commented
> Have you forgotten the naming convention? because It seems like your PR title does not format well and your PR description doesn't look well
sorry i forgot about it but now it is changed and also changed the PR description

2022-05-10 09:21 UTC, ncutixavier approved these changes

2022-05-10 09:21 UTC, merged