ft/profile page
atlp-rwanda/cabal-bn-fe pull request #18
Opened 2022-05-20 17:17 UTC by Gabin-ishimwe

2022-05-24 07:18 UTC, Tsa2341 requested changes
also check the date of birth input validattion.

and the email and app notification buttons functionality, when you unselect one all becomes unselected.

2022-05-24 07:18 UTC, Tsa2341 commented on tests/profile.test.js
> +    // moxios.stubRequest("POST", "/users/", {
remove commented code, do it in all the other files  also.

2022-05-24 07:18 UTC, Tsa2341 commented on src/components/input.js
> +  // const [value, setValue] = useState('');
remove commented code, do it in all the others files also

2022-05-24 07:18 UTC, Tsa2341 commented on src/redux/actions/location.action.js
> +      console.log(res)
try to remove all un needed console.logs

2022-05-24 07:18 UTC, Tsa2341 commented on src/redux/actions/location.action.js
> +      console.log(res)
do it also in all the other files also

2022-05-24 07:43 UTC, blandri approved these changes

2022-05-27 16:32 UTC, Code-250 approved these changes

2022-05-27 16:32 UTC, Code-250 approved these changes

2022-05-31 18:21 UTC, merged