#181339492: User-role-settings
atlp-rwanda/cabal-bn-fe pull request #19
Opened 2022-05-25 20:19 UTC by blandri

description

2022-05-27 13:18 UTC, Tsa2341 requested changes
Remove the scrolling on the page i think you it can fit and center without the scrolling.

2022-05-27 13:18 UTC, Tsa2341 commented on src/redux/actions/user_role_settings.action.js
> +// export const assignRoleActionError=(payload)=>{
remove commented lines, do it in all the others files also,

2022-05-27 13:18 UTC, Tsa2341 commented on src/redux/actions/user_role_settings.action.js
> +    console.log(users);
remove unnecesssary console.logs, do it in all the others files also,

2022-05-27 13:18 UTC, Tsa2341 commented on tests/user_role_settings.test.js
> +//   it('should test get all roles action',async()=>{
remove commented lines, do it in all the others files also,

2022-05-27 13:18 UTC, Tsa2341 commented on src/components/user_role.js
> +              // sx={{
remove commented lines, do it in all the others files also,

2022-06-01 06:57 UTC, Gabin-ishimwe approved these changes

2022-06-01 07:51 UTC, Code-250 approved these changes

2022-06-01 08:16 UTC, Eli250 approved these changes

2022-06-01 16:28 UTC, merged