Feature/read one trip request
atlp-rwanda/cabal-bn-fe pull request #24
Opened 2022-06-02 19:36 UTC by blandri

2022-06-06 09:58 UTC, Code-250 approved these changes

2022-06-06 15:14 UTC, Eli250 approved these changes

2022-06-07 09:38 UTC, ncutixavier commented
You must have updated the PR description & title since you push new changes. Ask @Eli250 or @Code-250 for reference

2022-06-07 11:57 UTC, ncutixavier commented
![image](https://user-images.githubusercontent.com/51375428/172373354-3495709a-b88c-4ce4-8c2a-fa8ba8cb39fd.png)
You should not fetch users when retrieving a single trip

2022-06-07 12:03 UTC, ncutixavier requested changes
Remember to change your PR Title to follow naming convention

2022-06-07 12:03 UTC, ncutixavier commented on src/routes/index.js
> +          <Route path="readone/:id/:role" element={<ReadOneTrip />} />
Change this route, It doesn't follow a naming convention.  Also, don't pass role in the params

2022-06-07 15:23 UTC, merged